---
version: '2'
services:
  consul:
    container_name: consul
    image: consul:latest
    command: "agent -server -bootstrap -ui -client=0.0.0.0 -log-level=debug"
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8302:8302'
      - '8400:8400'
      - '8500:8500'
      - '8600:53/udp'

  getenv:
    container_name: getenv
    image: vietwow/getenv:latest
    ports:
      - '80:80'
    depends_on:
      - consul
